# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twitter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtwitter.proto\x12\x07twitter\"#\n\x05Tweet\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\x12GetTimelineRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"5\n\x13GetTimelineResponse\x12\x1e\n\x06tweets\x18\x01 \x03(\x0b\x32\x0e.twitter.Tweet\"1\n\x10PostTweetRequest\x12\x1d\n\x05tweet\x18\x01 \x01(\x0b\x32\x0e.twitter.Tweet\"$\n\x11PostTweetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"9\n\x11\x46ollowUserRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x16\n\x0euser_to_follow\x18\x02 \x01(\t\"%\n\x12\x46ollowUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe5\x01\n\x0eTwitterService\x12H\n\x0bGetTimeline\x12\x1b.twitter.GetTimelineRequest\x1a\x1c.twitter.GetTimelineResponse\x12\x42\n\tPostTweet\x12\x19.twitter.PostTweetRequest\x1a\x1a.twitter.PostTweetResponse\x12\x45\n\nFollowUser\x12\x1a.twitter.FollowUserRequest\x1a\x1b.twitter.FollowUserResponseb\x06proto3')



_TWEET = DESCRIPTOR.message_types_by_name['Tweet']
_GETTIMELINEREQUEST = DESCRIPTOR.message_types_by_name['GetTimelineRequest']
_GETTIMELINERESPONSE = DESCRIPTOR.message_types_by_name['GetTimelineResponse']
_POSTTWEETREQUEST = DESCRIPTOR.message_types_by_name['PostTweetRequest']
_POSTTWEETRESPONSE = DESCRIPTOR.message_types_by_name['PostTweetResponse']
_FOLLOWUSERREQUEST = DESCRIPTOR.message_types_by_name['FollowUserRequest']
_FOLLOWUSERRESPONSE = DESCRIPTOR.message_types_by_name['FollowUserResponse']

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.Tweet)
  })
_sym_db.RegisterMessage(Tweet)

GetTimelineRequest = _reflection.GeneratedProtocolMessageType('GetTimelineRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTIMELINEREQUEST,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.GetTimelineRequest)
  })
_sym_db.RegisterMessage(GetTimelineRequest)

GetTimelineResponse = _reflection.GeneratedProtocolMessageType('GetTimelineResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTIMELINERESPONSE,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.GetTimelineResponse)
  })
_sym_db.RegisterMessage(GetTimelineResponse)

PostTweetRequest = _reflection.GeneratedProtocolMessageType('PostTweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTTWEETREQUEST,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.PostTweetRequest)
  })
_sym_db.RegisterMessage(PostTweetRequest)

PostTweetResponse = _reflection.GeneratedProtocolMessageType('PostTweetResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSTTWEETRESPONSE,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.PostTweetResponse)
  })
_sym_db.RegisterMessage(PostTweetResponse)

FollowUserRequest = _reflection.GeneratedProtocolMessageType('FollowUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWUSERREQUEST,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.FollowUserRequest)
  })
_sym_db.RegisterMessage(FollowUserRequest)

FollowUserResponse = _reflection.GeneratedProtocolMessageType('FollowUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOWUSERRESPONSE,
  '__module__' : 'twitter_pb2'
  # @@protoc_insertion_point(class_scope:twitter.FollowUserResponse)
  })
_sym_db.RegisterMessage(FollowUserResponse)

_TWITTERSERVICE = DESCRIPTOR.services_by_name['TwitterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TWEET._serialized_start=26
  _TWEET._serialized_end=61
  _GETTIMELINEREQUEST._serialized_start=63
  _GETTIMELINEREQUEST._serialized_end=112
  _GETTIMELINERESPONSE._serialized_start=114
  _GETTIMELINERESPONSE._serialized_end=167
  _POSTTWEETREQUEST._serialized_start=169
  _POSTTWEETREQUEST._serialized_end=218
  _POSTTWEETRESPONSE._serialized_start=220
  _POSTTWEETRESPONSE._serialized_end=256
  _FOLLOWUSERREQUEST._serialized_start=258
  _FOLLOWUSERREQUEST._serialized_end=315
  _FOLLOWUSERRESPONSE._serialized_start=317
  _FOLLOWUSERRESPONSE._serialized_end=354
  _TWITTERSERVICE._serialized_start=357
  _TWITTERSERVICE._serialized_end=586
# @@protoc_insertion_point(module_scope)
